### ISSUE TITLE
[WG-gmu] Gatsby Site Setup

### ISSUE THREAD

**Issue by SpokieKid** [blueskyCommunity/aozora#11]
Imported from Gitlab. See [Original](https://gitlab.com/bluesky-community/flow/-/issues/1).

**Comment by gvelez17** [comment]
hey do we still need this? @macintoshhelper I'm trying to remember, did you help import this from Taiga to gitlab (and now its here) or was there an original reason we wanted Gatsby?

**Comment by macintoshhelper** [comment]
This was in the GitLab Projects board; GitLab automatically creates issues for each item in a project, which is a bit annoying. GitHub Projects boards don’t make issues for each item.

I’ve already setup Gatsby for the Gun Modular UI project, I'll push up some more work shortly.
