### ISSUE TITLE
Transcribe @bluesky_commons Twitter Space warmup - via machine transcription service

### ISSUE THREAD

**Issue by schwentker** [blueskyCommunity/aozora#14]
The @bluesky_commons hosted a twitter spaces warmup. https://twitter.com/bluesky_commons/status/1438741586729263107

We have the recording which we'd like transcribe:  

(https://drive.google.com/file/d/176DRBtiwg_VcCfLfn6sMShNEXnTektCN/view?usp=sharing)

A machine transcription probably is sufficient. 

One can perhaps use https://get.otter.ai/ tho need to translate the .ts file to something like .mpg 

The output could be put into a google doc which we'll share with the speakers.

The speakers may make edits.

Then we can publish the transcription on something more decentralized then google docs.

**Comment by DevMenna** [comment]
hey Robert!
I think twitter has already removed the meet since it's been a while do you have a copy of it that I can get transcribed for you?

**Comment by DevMenna** [comment]
https://drive.google.com/drive/folders/19ol2cBIY5cNqpTd57-ZU1mGjP4qg1-GK?usp=sharing
all done!
