### ISSUE TITLE
homepage: Add link to "mnm" project

### ISSUE THREAD

**Issue by networkimprov** [blueskyCommunity/aozora#17]
Hi, I'm the author of "mnm", a decentralized store-and-forward message service based on an open protocol (TMTP). It's open source.

Would you be willing to add a link to my project on the bluesky-community.net homepage, under Tools and Apps?

Website: https://mnmnotmail.org
Server: https://github.com/networkimprov/mnm
Client: https://github.com/networkimprov/mnm-hammer

**Comment by networkimprov** [comment]
cc @timbray @gvelez17

**Comment by gvelez17** [comment]
hey Robert not sure if you actually emailed him back, you might have to do
it in github

**Comment by gvelez17** [comment]
hey @networkimprov sorry for the delay in response - so decision is that it would not right now be on the home page of the blueskycommunity.net, but can be linked into the ecosystem docs - possibly an enlarged version of the main ecosystem doc.  Can you submit this as a PR to https://github.com/blueskyCommunity/aozora/blob/main/ECOSYSTEM/suggestions.md ?

**Comment by gvelez17** [comment]
@DevMenna lets leave this open for now to give @networkimprov a chance to submit the pr

**Comment by networkimprov** [comment]
Hi Golda, thanks for getting back to me! I'll create the PR.

Is the [Ecosystem Overview](https://gitlab.com/bluesky-community1/decentralized-ecosystem/-/blob/master/README.md) posted on any Bluesky website? Or just in the GitLab repo?

Asking, because if mnm/TMTP gets promoted out of "Suggestions", it would be nice to be listed on a website, vs a repo, as the repo hosts add `rel="nofollow"` to hrefs :-/

BTW, I had never seen that GitLab site when reading about Bluesky; what places link to it?

FWIW, TMTP doesn't define a universal identity scheme the way that email & Matrix do. Rather, it can leverage any third party identity and/or authentication credential for registration/login, at the discretion of each TMTP site. (Currently it offers OpenID Connect.) More on the [mnm FAQ](https://mnmnotmail.org/faq.html).

**Comment by networkimprov** [comment]
PR added! See #30.

I'm happy to create a detailed page for it if you plan to promote it to the main Ecosystem list!

**Comment by networkimprov** [comment]
PR merged, thanks!

Is there a plan to review Suggestions, and promote them to the Ecosystem pages?
