### ISSUE TITLE
Translation Task!  COPY THIS TASK

### ISSUE THREAD

**Issue by SpokieKid** [blueskyCommunity/aozora#4]
We need the front page at https://blueskycommunity.net translated idiomatically into any language you might know!

We have translations currently for Arabic, Japanese and Burmese - for any other language, please make a copy of this task (or just a brand new task) and attach your translation to it.

Here is an example of the Japanese translation in spreadsheet format https://docs.google.com/spreadsheets/d/1TIIB6TilAs7jl1rakDzHkTisrSlqmTBkzfw9ZqKSshs/edit#gid=0

Thank you!

Imported from taiga. See [Original](http://taiga.whatscookin.us/project/bluesky-community/us/4?kanban-status=168).

**Comment by jamesharden3762** [comment]
Hi, this is the Chinese translation I did, please check it
[blueskycommunity.net into Chinese.xlsx](https://github.com/blueskyCommunity/aozora/files/7738215/blueskycommunity.net.into.Chinese.xlsx)
